export const NOTIFICATION_TYPES = {
  VIP_PURCHASE: "VIP_PURCHASE",
  VIP_EXPIRY: "VIP_EXPIRY",
  JOB_STATUS_CHANGE: "JOB_STATUS_CHANGE",
  NEW_APPLICANT: "NEW_APPLICANT",
  APPLICATION_STATUS_CHANGE: "APPLICATION_STATUS_CHANGE",
  CANDIDATE_APPLIED: "CANDIDATE_APPLIED",
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
};